version: "3.9"

services:
  database:
    image: mongo:5.0.8
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    networks:
      - tech-notes-network
    expose:
      - "27017"
    volumes:
      - ./tmp/data/mongodb:/data/mongodb
    deploy:
      resources:
        limits:
          memory: 250M
        reservations:
          memory: 100M

  tech-notes-api:
    image: ccpdev/tech-notes:latest
    restart: on-failure
    depends_on:
      - database
    environment:
      PORT: $PORT
      MONGODB_CONN_URI: $MONGODB_CONN_URI
      MONGODB_DATABASE: $MONGODB_DATABASE
    networks:
      - tech-notes-network
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 75M

  nginx:
    image: nginx:1.21.6
    restart: on-failure
    depends_on:
      - tech-notes-api
    networks:
      - tech-notes-network
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          memory: 25M
        reservations:
          memory: 15M
      
networks:
  tech-notes-network:
    driver: bridge
