version: "3.9"

services:
  database:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    ports:
      - "27017:27017"
    volumes:
      - ./tmp/data/mongodb:/data/mongodb
    networks:
      - public-tech-notes-network
    deploy:
      resources:
        limits:
          memory: 250M
        reservations:
          memory: 100M

  public-tech-notes:
    image: ccpdev/public-tech-notes
    restart: on-failure
    environment:
      MONGODB_CONN_URI: $MONGODB_CONN_URI
      MONGODB_DATABASE: $MONGODB_DATABASE
    expose:
      - "8080"
    networks:
      - public-tech-notes-network
    depends_on:
      - database
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 75M

  nginx:
    image: nginx:latest
    restart: on-failure
    ports:
      - "80:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - public-tech-notes-network
    depends_on:
      - public-tech-notes
    deploy:
      resources:
        limits:
          memory: 30M
        reservations:
          memory: 15M
      
networks:
  public-tech-notes-network:
    driver: bridge
